[versions]
# Dependencies
bom-newest = "1.37"
cloud-paper = "2.0.0-beta.11"
coreprotect = "22.4"
paper = "1.21.6-R0.1-SNAPSHOT"
plotsquared = "7.3.8"
reflection-remapper = "0.1.3"
viaversion-api = "5.4.2-SNAPSHOT"
worldguard-bukkit = "7.0.9-SNAPSHOT"
zstd-jni = "1.5.5-4"

# Plugins
paperweight-userdev = "2.0.0-beta.17"
run-paper = "2.3.1"
shadow = "8.1.7"

[libraries]
bom-newest = { group = "com.intellectualsites.bom", name = "bom-newest", version.ref = "bom-newest" }
cloud-paper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud-paper" }
coreprotect = { group = "net.coreprotect", name = "coreprotect", version.ref = "coreprotect" }
plotsquared-bukkit = { group = "com.intellectualsites.plotsquared", name = "plotsquared-bukkit", version.ref = "plotsquared" }
plotsquared-core = { group = "com.intellectualsites.plotsquared", name = "plotsquared-core", version.ref = "plotsquared" }
reflection-remapper = { group = "xyz.jpenilla", name = "reflection-remapper", version.ref = "reflection-remapper" }
viaversion-api = { group = "com.viaversion", name = "viaversion-api", version.ref = "viaversion-api" }
worldguard-bukkit = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref = "worldguard-bukkit" }
zstd-jni = { group = "com.github.luben", name = "zstd-jni", version = "1.5.5-4" }

[plugins]
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
